version: "3.8"
services:
    client:
        build: ./frontend
        expose: 
            - 3000
        ports: 
            - "3000:3000"
        volumes:
            - './frontend:/usr/src/frontend'
            - '/usr/src/frontend/node_modules'
        environment: 
            - CHOKIDAR_USEPOLLING=true
            - NODE_ENV=development
        stdin_open: true
        depends_on:
            - flaskapp
        networks:
            - frontend
    flaskapp:
        build: ./flask
        expose: 
            - 5000
        ports: 
            - "5000:5000"
        environment: 
            MONGO: 'mongodb://mongodb:27017'
        depends_on:
            - mongodb
        networks:
            - backend
            - frontend
    mongodb:
        image: mongo
        expose:
            - 27017
        ports:
            - "27017:27017"
        volumes:
            - /data/db:/data/db
        networks:
            - fetcher
            - backend
    fetcher:
        build: ./fetcher
        environment: 
            MONGO: 'mongodb://mongodb:27017'
            API_KEY: '&key=74a3284f-d0de-497d-a116-755c7fc7868a'
        depends_on: 
            - mongodb
        networks: 
            - fetcher

networks:
    frontend:
        driver: bridge
    backend:
        driver: bridge
    fetcher:
        driver: bridge



        
